Repository webfrontier-intern-20231002-20231031/todo-team-a, pull requests merged in 2023-10, with the labels that each got.

#47 深夜作業まとめ
  front/todo/README.md
  front/todo/db.json
  front/todo/mock/db.json
  front/todo/package-lock.json
  front/todo/package.json
  front/todo/pages/components/Navbar.tsx
  front/todo/tailwind.config.js
  front/todo/tailwind.config.ts
Labels: Front

#51 Component partitioning
  .gitignore
  front/todo/pages/components/Navbar.tsx
  front/todo/pages/components/card/todocard.tsx
  front/todo/pages/components/form/selector.tsx
  front/todo/pages/components/modal/modal1.tsx
  front/todo/pages/components/modal/modal2.tsx
  front/todo/pages/components/svg_button/deleteButton.tsx
  front/todo/pages/components/svg_button/reload.tsx
  front/todo/pages/components/svg_button/sort.tsx
Labels: Front, Front-API-test

#52 リストのソート機能を作る #18
  front/todo/mock/db.json
  front/todo/pages/components/Navbar.tsx
  front/todo/pages/components/svg_button/reload.tsx
  front/todo/pages/components/svg_button/sort.tsx
Labels: Front

#67 create/read/delete api
  back/src/api/v1/todo.py
  back/src/crud/tag.py
  back/src/crud/todo.py
  back/src/logging.json
  back/src/schemas/schema.py
Labels: FastAPI

#70 #69 z-index問題
  front/todo/pages/components/Navbar.tsx
Labels: bug, Front

#77 make update api
  back/src/crud/todo.py
Labels: FastAPI

#79 fix soft delete - tag table
  back/migration/versions/93a7693ea2dd_postgres_fix_tag_table_soft_delete.py
  back/src/models/tag.py
  back/src/models/todo.py
Labels: FastAPI

#80 Creat todo
  back/migration/versions/39679cc997f7_postgres_create_todo_table.py
  front/todo/pages/api/todoCrud/todo.ts
  front/todo/pages/api/ui/getTag.ts
  front/todo/pages/api/ui/getTodo.ts
  front/todo/pages/components/Navbar.tsx
  front/todo/pages/components/card/todocard.tsx
  front/todo/pages/components/form/checobox.tsx
  front/todo/pages/components/modal/modal1.tsx
Labels: Front, Front-NextServer

#81 京都の眠れない夜
  back/src/crud/todo.py
  front/todo/package-lock.json
  front/todo/package.json
  front/todo/pages/api/todoCrud/completed.ts
  front/todo/pages/api/todoCrud/delete.ts
  front/todo/pages/api/todoCrud/todo.ts
  front/todo/pages/api/ui/getTag.ts
  front/todo/pages/api/ui/getTodo.ts
  front/todo/pages/atoms.tsx
  front/todo/pages/components/LoginFream.tsx
  front/todo/pages/components/Navbar.tsx
  front/todo/pages/components/card/todocard.tsx
  front/todo/pages/components/modal/modal1.tsx
  front/todo/pages/components/modal/modal2.tsx
  front/todo/pages/index.tsx
  front/todo/pages/todo.tsx
Labels: Front-NextServer

#84 todo/tagの論理削除を実装しました
  back/src/crud/tag.py
  back/src/crud/todo.py
Labels: FastAPI

#86 Todo/Tagのget系で論理削除されたものを除外しました
  back/src/crud/tag.py
  back/src/crud/todo.py
Labels: FastAPI

#88 tagのみの取得apiを作成しました
  back/src/api/v1/tag.py
Labels: FastAPI

#94 userテーブルを作成しました
  back/migration/versions/3c516ab54875_postgres_add_user_table.py
  back/migration/versions/ca01e2aa05d2_postgres_add_user_table.py
  back/src/models/todo.py
  back/src/models/user.py
Labels: FastAPI

#98 userを作成するapiを作りました
  back/src/api/v1/user.py
  back/src/app/router.py
  back/src/crud/user.py
  back/src/models/user.py
  back/src/schemas/schema.py
Labels: FastAPI

#101 userテーブルの構造変更と、todo/tagテーブルの変更
  back/migration/versions/1885e3c6913d_postgres_fix_table.py
  back/migration/versions/1d2f43a2d4a7_postgres_fix_table.py
  back/migration/versions/d13f86395cea_postgres_fix_table.py
  back/src/models/tag.py
  back/src/models/todo.py
  back/src/models/user.py
Labels: FastAPI

#102 Sort fix
  .vscode/launch.json
  front/todo/package-lock.json
  front/todo/package.json
  front/todo/pages/api/ui/getTodo.ts
  front/todo/pages/atoms.tsx
  front/todo/pages/components/Navbar.tsx
  front/todo/pages/components/card/todocard.tsx
  front/todo/pages/components/modal/modal1.tsx
  front/todo/pages/components/modal/modal2.tsx
  front/todo/pages/components/svg_button/sort.tsx
Labels: Front, Front-NextServer

#103 userテーブルと他のテーブル間のリレーションを切断
  back/migration/versions/833f42aafb2a_postgres_fix_relationship_table.py
  back/src/api/v1/user.py
  back/src/crud/user.py
  back/src/models/tag.py
  back/src/models/todo.py
  back/src/models/user.py
  back/src/schemas/schema.py
Labels: FastAPI
